"""empty message

Revision ID: 26d1f7b86528
Revises: 
Create Date: 2020-11-27 16:50:20.375034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d1f7b86528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.Text(), nullable=False),
    sa.Column('departure_time', sa.Text(), nullable=False),
    sa.Column('day_week', sa.Text(), nullable=False),
    sa.Column('number_seats', sa.Text(), nullable=False),
    sa.Column('route', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
